source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'AFNetworking'
pod 'SBJson4', '~> 4.0.0'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'PaymentKit'
pod 'KASlideShow'
